[package]
name = "irc-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"], default-features = true }

drax.workspace = true

irc-common = { path = "../common" }
